### PR TITLE
fix bug: shop serializers reference state, big_city, city as field not relation

### PR DESCRIPTION
**Pull request by likecodingloveproblems**
shop State, BigCity, City have changed to Foriegn key
So their serializers must be modified.

### CODE REVIEW

**Comment by PouryaMansouri** [comment]
I test this branch locally and still, we have "Object of type State is not JSON serializable".

**Comment by PouryaMansouri** [comment]
@likecodingloveproblems 
I test this branch locally and still, we have "Object of type State is not JSON serializable".

**Comment by PouryaMansouri** [comment]
this API : 
{{host}}/api/v1/shop/{{shop_slug}}/settings/

**Review by PouryaMansouri — CHANGES_REQUESTED** [review]
Please check postman, you can see the error persists.
{{host}}/api/v1/shop/{{shop_slug}}/settings/
and 
{{host}}/api/v1/shop/{{shop_slug}}/products/

you didn't change profile model,
this {{host}}/api/v1/get-user-info/ api still return str of city and etc...

**Comment by likecodingloveproblems** [comment]
@PouryaMansouri please review this

**Review by PouryaMansouri — APPROVED** [review]

**Pull request merged**
