### PR TITLE
DB schema cleanup

### PR DESCRIPTION
**Pull request by likecodingloveproblems**

### CODE REVIEW

**Comment by mohsenone** [comment]
فایل Migration رو نمیخواستی اضافه کنی؟

**Review by mohsenone — APPROVED** [review]

**Comment by likecodingloveproblems** [comment]
@mohsenone first we check data with SQL and we doubt that data cleaning is a long time process so we find dirty data and by the help of @saman7799  and the operation team some cleaning operations were done.
this day I check the data and see that dirty data is created!
so I write another type of migration and I use dummy data objects.

**Review by mohsenone — APPROVED** [review]

**Comment by mohsenone** [comment]
Please, Resolve conflicts @likecodingloveproblems

**Comment by likecodingloveproblems** [comment]
these changes change our point of view with data, It seems many operations will be blocked, we must review processes that delete data, they will be stopped now!
So is there any process to remove a product object, shop object, Invoice and InvoiceItem object?

**Comment by likecodingloveproblems** [comment]
I will merge and deploy it next week, Saturday will god help :+1:

**Pull request merged**
